### ISSUE TITLE
After vagrant box add laravel/homestead, what do I do

### ISSUE THREAD

**Issue by csheare** [AlexanderSix/cuhackit-laravel#1]
==> box: Loading metadata for box 'laravel/homestead'
    box: URL: https://vagrantcloud.com/laravel/homestead
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) hyperv
2) parallels
3) virtualbox
4) vmware_desktop

**Comment by AlexanderSix** [comment]
Fixed in commit 5c7aa51864da4483e6941c985efc32804ac17439
