### ISSUE TITLE
Navigate to the Laravel application directory. 

### ISSUE THREAD

**Issue by csheare** [AlexanderSix/cuhackit-laravel#4]
In this specific case: cd /home/vagrant/code/cuhackit-laravel

*should be In this specific case: cd /home/vagrant/code/cuhackit-laravel/app ??

**Comment by AlexanderSix** [comment]
The directory `/home/vagrant/code/cuhackit-laravel` is the Laravel application directory on the Vagrant machine. The subdirectory `/home/vagrant/code/cuhackit-laravel/app` is a directory created by the Laravel install that holds Models, Controllers, Contracts, etc.
